CREATE TABLE contributor_trust_stats (
    user_id BIGINT PRIMARY KEY,
    trust_score INTEGER NOT NULL DEFAULT 1000,
    trust_tier VARCHAR(20) NOT NULL DEFAULT 'NEW',
    reviewed_count INTEGER NOT NULL DEFAULT 0,
    approved_count INTEGER NOT NULL DEFAULT 0,
    approved_with_image_count INTEGER NOT NULL DEFAULT 0,
    rejected_total_count INTEGER NOT NULL DEFAULT 0,
    rejected_mistake_count INTEGER NOT NULL DEFAULT 0,
    rejected_bad_count INTEGER NOT NULL DEFAULT 0,
    rejected_fraud_count INTEGER NOT NULL DEFAULT 0,
    last_event_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contributor_trust_stats_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_contributor_trust_stats_tier CHECK (trust_tier IN ('RISKY', 'NEW', 'RELIABLE', 'TRUSTED', 'HIGH_TRUST')),
    CONSTRAINT chk_contributor_trust_stats_score CHECK (trust_score >= 0)
);

CREATE INDEX idx_contributor_trust_stats_score
    ON contributor_trust_stats (trust_score DESC, reviewed_count DESC, last_event_at ASC);

CREATE TABLE contributor_trust_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    submission_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    trust_delta INTEGER NOT NULL,
    previous_score INTEGER NOT NULL,
    new_score INTEGER NOT NULL,
    metadata TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contributor_trust_events_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_contributor_trust_events_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_contributor_trust_events_review FOREIGN KEY (review_id) REFERENCES submission_reviews(id),
    CONSTRAINT uq_contributor_trust_events_review UNIQUE (review_id),
    CONSTRAINT chk_contributor_trust_events_new_score CHECK (new_score >= 0)
);

CREATE INDEX idx_contributor_trust_events_user_created_at
    ON contributor_trust_events (user_id, created_at DESC);
