CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE supermarkets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_supermarkets_name UNIQUE (name)
);

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supermarket_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    address_line VARCHAR(180),
    city VARCHAR(120),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_branches_supermarket FOREIGN KEY (supermarket_id) REFERENCES supermarkets(id)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    brand VARCHAR(160),
    normalized_name VARCHAR(200) NOT NULL,
    normalized_brand VARCHAR(160) NOT NULL,
    barcode VARCHAR(64),
    image_url VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT uq_products_barcode UNIQUE (barcode)
);

CREATE INDEX idx_products_normalized_name_brand ON products (normalized_name, normalized_brand);

CREATE TABLE product_nutrition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    calories DECIMAL(8,2),
    protein_g DECIMAL(8,2),
    carbs_g DECIMAL(8,2),
    fat_g DECIMAL(8,2),
    serving_size VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_nutrition_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT uq_product_nutrition_product UNIQUE (product_id)
);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payload TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_submissions_type CHECK (type IN ('PRODUCT', 'PRICE', 'NUTRITION')),
    CONSTRAINT chk_submissions_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_submissions_status_created_at ON submissions (status, created_at);

CREATE TABLE submission_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    admin_user_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_reviews_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_submission_reviews_admin FOREIGN KEY (admin_user_id) REFERENCES users(id),
    CONSTRAINT chk_submission_reviews_action CHECK (action IN ('APPROVED', 'REJECTED'))
);

CREATE TABLE verified_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    supermarket_id BIGINT NOT NULL,
    branch_id BIGINT,
    price DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'MKD',
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    submission_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_verified_prices_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_verified_prices_supermarket FOREIGN KEY (supermarket_id) REFERENCES supermarkets(id),
    CONSTRAINT fk_verified_prices_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_verified_prices_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT chk_verified_prices_source CHECK (source_type IN ('SYSTEM', 'USER')),
    CONSTRAINT chk_verified_prices_amount_positive CHECK (price > 0)
);

CREATE INDEX idx_verified_prices_product_supermarket_observed_desc
    ON verified_prices (product_id, supermarket_id, observed_at DESC);
