CREATE TABLE submission_edits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    admin_user_id BIGINT NOT NULL,
    before_payload TEXT NOT NULL,
    after_payload TEXT NOT NULL,
    reason TEXT,
    changed_field_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_edits_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_submission_edits_admin FOREIGN KEY (admin_user_id) REFERENCES users(id)
);

CREATE INDEX idx_submission_edits_submission_created_at
    ON submission_edits (submission_id, created_at);

CREATE TABLE submission_ai_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT,
    user_id BIGINT,
    analysis_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    model VARCHAR(120),
    prompt_version VARCHAR(60),
    source_image_url VARCHAR(500),
    extracted_payload TEXT,
    confidence DECIMAL(5,4),
    flags TEXT,
    warnings TEXT,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_ai_analysis_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_submission_ai_analysis_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_submission_ai_analysis_type CHECK (analysis_type IN ('DRAFT', 'REVIEW', 'HEURISTIC')),
    CONSTRAINT chk_submission_ai_analysis_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'UNAVAILABLE'))
);

CREATE INDEX idx_submission_ai_analysis_submission_created_at
    ON submission_ai_analysis (submission_id, created_at DESC);

CREATE TABLE contributor_stats (
    user_id BIGINT PRIMARY KEY,
    approved_product_count INTEGER NOT NULL DEFAULT 0,
    approved_price_count INTEGER NOT NULL DEFAULT 0,
    approved_nutrition_count INTEGER NOT NULL DEFAULT 0,
    approved_total_count INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    score INTEGER NOT NULL DEFAULT 0,
    last_event_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contributor_stats_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_contributor_stats_score
    ON contributor_stats (score DESC, approved_total_count DESC, last_event_at ASC);

CREATE TABLE contributor_score_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    submission_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    points INTEGER NOT NULL,
    metadata TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contributor_score_events_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_contributor_score_events_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT fk_contributor_score_events_review FOREIGN KEY (review_id) REFERENCES submission_reviews(id)
);

CREATE INDEX idx_contributor_score_events_user_created_at
    ON contributor_score_events (user_id, created_at DESC);

CREATE INDEX idx_contributor_score_events_created_at
    ON contributor_score_events (created_at DESC);

CREATE TABLE import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    job_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    summary TEXT,
    total_rows INTEGER NOT NULL DEFAULT 0,
    valid_rows INTEGER NOT NULL DEFAULT 0,
    invalid_rows INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_import_jobs_admin FOREIGN KEY (admin_user_id) REFERENCES users(id),
    CONSTRAINT chk_import_jobs_type CHECK (job_type IN ('CATALOG_DRY_RUN', 'CATALOG_COMMIT')),
    CONSTRAINT chk_import_jobs_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE import_job_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    raw_row TEXT,
    error_message TEXT,
    created_entity_type VARCHAR(30),
    created_entity_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_import_job_rows_job FOREIGN KEY (job_id) REFERENCES import_jobs(id),
    CONSTRAINT chk_import_job_rows_status CHECK (status IN ('VALID', 'INVALID', 'IMPORTED', 'SKIPPED'))
);

CREATE INDEX idx_import_job_rows_job_row_number
    ON import_job_rows (job_id, row_number);
