CREATE TABLE password_reset_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_email VARCHAR(255) NOT NULL,
    user_id BIGINT,
    token_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_by_admin_user_id BIGINT,
    decision_reason TEXT,
    decision_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_requests_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_password_reset_requests_admin FOREIGN KEY (decided_by_admin_user_id) REFERENCES users(id),
    CONSTRAINT uq_password_reset_requests_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_password_reset_requests_status CHECK (status IN ('PENDING', 'APPROVED', 'DENIED', 'COMPLETED', 'EXPIRED'))
);

CREATE INDEX idx_password_reset_requests_status_created_at
    ON password_reset_requests (status, created_at DESC);

CREATE INDEX idx_password_reset_requests_email_created_at
    ON password_reset_requests (requester_email, created_at DESC);
