ALTER TABLE submissions DROP CONSTRAINT chk_submissions_type;

ALTER TABLE submissions
    ADD CONSTRAINT chk_submissions_type
    CHECK (type IN ('PRODUCT', 'PRICE', 'NUTRITION', 'AVAILABILITY'));

CREATE TABLE product_market_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    supermarket_id BIGINT NOT NULL,
    available BOOLEAN NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    submission_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_market_availability_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_product_market_availability_supermarket FOREIGN KEY (supermarket_id) REFERENCES supermarkets(id),
    CONSTRAINT fk_product_market_availability_submission FOREIGN KEY (submission_id) REFERENCES submissions(id),
    CONSTRAINT chk_product_market_availability_source CHECK (source_type IN ('SYSTEM', 'USER'))
);

CREATE INDEX idx_product_market_availability_product_supermarket_observed_desc
    ON product_market_availability (product_id, supermarket_id, observed_at DESC);

CREATE INDEX idx_product_market_availability_product_observed_desc
    ON product_market_availability (product_id, observed_at DESC);
